name: Cleanup old branches
on:
  workflow_dispatch: {}

jobs:
  housekeeping:
    name: Cleanup old branches
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
      - name: Run delete-old-branches-action
        uses: beatlabs/delete-old-branches-action@4eeeb8740ff8b3cb310296ddd6b43c3387734588  # v0.0.11
        with:
          repo_token: ${{ github.token }}
          date: 1 day ago
          dry_run: false
          delete_tags: true
          minimum_tags: 5
          extra_protected_branch_regex: ^(main)$
          extra_protected_tag_regex: ^v.*
          exclude_open_pr_branches: true
